name = "vaulttask-api-worker"
main = "cloudflare_worker.js"
compatibility_date = "2026-04-16"
account_id = "3cf3dea881cea4cdbe2aee3b5f2c8225"

[[d1_databases]]
binding = "DB"
database_name = "vaulttask-db"
database_id = "8d2ff36d-c37b-4ae5-b18e-3771142fb7c1"

[durable_objects]
bindings = [
  { name = "BOARD_HUB", class_name = "BoardHub" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["BoardHub"]

# [ai]
# binding = "AI"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "calenda-assets"
