// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmpEBLMOPw8pcSJpd4d7TCI3Sj_m4hwnc',
    appId: '1:294337832265:web:b3faf535b42fc7664c2698',
    messagingSenderId: '294337832265',
    projectId: 'calenda-ai-app',
    authDomain: 'calenda-ai-app.firebaseapp.com',
    storageBucket: 'calenda-ai-app.firebasestorage.app',
    measurementId: 'G-4H6K9Y38LM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAB7Mqm4FirYGFM81j9X_WZAN0jr2zLE0',
    appId: '1:294337832265:android:8f2e1193a125c9124c2698',
    messagingSenderId: '294337832265',
    projectId: 'calenda-ai-app',
    storageBucket: 'calenda-ai-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD37G1Umsa_N9h_PggpbapjYeanMMdXnTQ',
    appId: '1:294337832265:ios:50bd10aa415e13a84c2698',
    messagingSenderId: '294337832265',
    projectId: 'calenda-ai-app',
    storageBucket: 'calenda-ai-app.firebasestorage.app',
    iosClientId: '294337832265-rhapvjri8coucajkebkjnv3nfrkupv3c.apps.googleusercontent.com',
    iosBundleId: 'com.example.myAiAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD37G1Umsa_N9h_PggpbapjYeanMMdXnTQ',
    appId: '1:294337832265:ios:50bd10aa415e13a84c2698',
    messagingSenderId: '294337832265',
    projectId: 'calenda-ai-app',
    storageBucket: 'calenda-ai-app.firebasestorage.app',
    iosClientId: '294337832265-rhapvjri8coucajkebkjnv3nfrkupv3c.apps.googleusercontent.com',
    iosBundleId: 'com.example.myAiAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmpEBLMOPw8pcSJpd4d7TCI3Sj_m4hwnc',
    appId: '1:294337832265:web:8825245d47e66af24c2698',
    messagingSenderId: '294337832265',
    projectId: 'calenda-ai-app',
    authDomain: 'calenda-ai-app.firebaseapp.com',
    storageBucket: 'calenda-ai-app.firebasestorage.app',
    measurementId: 'G-VK669TZLB0',
  );
}
